name: SonarQube

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - "release/**"
    paths:
      - "web/**"
      - "!.github/workflows/**"

permissions:
  contents: read

jobs:
  sonar-scan:
    name: "SonarQube static Analysis"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "SonarQube Scan"
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          projectBaseDir: web

      - name: "SonarQube Quality Gate check"
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
          scanMetadataReportFile: "./web/.scannerwork/report-task.txt"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
