name: Release NPM Packages

on:
    workflow_call:
        inputs:
            node-version:
                required: true
                type: string
                description: "GitHub organization name"
            manifest_repo:
                required: true
                type: string
                description: "Repository containing the deployment manifests"
        secrets:
            DEPLOYMENT_APP_ID:
                required: true
                description: "GitHub App ID for deployment"
            DEPLOYMENT_APP_PRIVATE_KEY:
                required: true
                description: "GitHub App Private Key for deployment"

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node-version }}
                  cache: "npm"
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
            - run: npm run build
            - run: npx changeset publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
